// @generated by tests/testgen.py from tests/run_all_instrs_all_modes.s - do not edit.
// Regenerate with: python3 tests/testgen.py

use std::sync::Mutex;

use vea_sim::{assembler, memory, onestep, shared};

// Tests in one file share a process and the global simulator memory, so they
// run one at a time. Separate .s files are separate test binaries (separate
// processes) and do not contend.
static LOCK: Mutex<()> = Mutex::new(());

const SOURCE: &str =
    include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/tests/run_all_instrs_all_modes.s"));

// (1-based instruction index, source line, [(reg, value)]) - checked every time
// that instruction retires.
const INLINE: &[(usize, u32, &[(usize, u64)])] = &[
    (1, 7, &[(1, 100)]),
    (2, 8, &[(2, 100)]),
    (3, 9, &[(3, 105)]),
    (4, 10, &[(4, 200)]),
    (5, 11, &[(5, 100)]),
    (6, 12, &[(6, 100)]),
    (7, 13, &[(7, 103)]),
    (8, 14, &[(8, 0)]),
    (9, 15, &[(9, 18446744073709551615)]),
    (10, 16, &[(10, 200)]),
    (11, 17, &[(11, 50)]),
    (12, 18, &[(12, 18446744073709551615)]),
    (13, 19, &[(13, 300)]),
    (14, 20, &[(14, 25)]),
    (15, 23, &[(20, 16384)]),
    (17, 25, &[(1, 0)]),
    (18, 26, &[(1, 100)]),
    (20, 28, &[(15, 105)]),
];

// (retired-instruction count, source line, [(reg, value)]) - from `;= at N:`.
const AT_COUNT: &[(u64, u32, &[(usize, u64)])] = &[

];

// (source line, [(reg, value)]) - from `;= final:`, checked once halted.
const FINAL: (u32, &[(usize, u64)]) = (31, &[(1, 100), (12, 18446744073709551615), (14, 25), (15, 105)]);

const CAP: u64 = 100_000;

#[test]
fn run_all_instrs_all_modes() {
    let _guard = LOCK.lock().unwrap_or_else(|e| e.into_inner());
    memory::reset();
    let (image, rows) = assembler::assemble_listing(SOURCE).expect("program assembles");
    memory::load(0, &image).expect("image loads");
    let mut cpu = onestep::Processor::new();

    // Resolve each annotated instruction index to the address it loaded at.
    let inline: Vec<(u64, u32, &[(usize, u64)])> = INLINE
        .iter()
        .map(|&(idx, line, checks)| (rows[idx - 1].addr, line, checks))
        .collect();

    let mut steps = 0u64;
    while !cpu.halted() && steps < CAP {
        let pc = cpu.pc;
        cpu.cycle(1).expect("instruction executes without a fault");
        steps += 1;
        let (regs, completed) =
            shared::with(|s| (s.snapshot.regs, s.snapshot.completed_instrs));

        for &(addr, line, checks) in &inline {
            if addr == pc {
                for &(reg, want) in checks {
                    assert_eq!(regs[reg], want, "line {line}: r{reg} (pc {addr:#x})");
                }
            }
        }
        for &(count, line, checks) in AT_COUNT {
            if count == completed {
                for &(reg, want) in checks {
                    assert_eq!(regs[reg], want, "line {line}: r{reg} at instruction {count}");
                }
            }
        }
    }

    assert!(cpu.halted(), "program did not halt within {CAP} instructions");

    let regs = shared::with(|s| s.snapshot.regs);
    let (line, checks) = FINAL;
    for &(reg, want) in checks {
        assert_eq!(regs[reg], want, "line {line}: r{reg} at halt");
    }
}
