// @generated by tests/testgen.py - do not edit.
// Regenerate with: python3 tests/testgen.py

use std::io::Write;
use std::path::Path;
use std::process::{Command, Stdio};

// (file name, md5sum) for every tests/*.s when the tests were generated.
const SOURCES: &[(&str, &str)] = &[
    ("run_all_instrs_all_modes.s", "c0c2b41998de6968f49e5d615c2341e3"),
    ("sample_basics.s", "4e95d761b1058c52f59b54aa676c0bc8"),
];

// Shell out to md5sum (same digest the generator baked in).
fn md5(data: &[u8]) -> String {
    let mut child = Command::new("md5sum")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .expect("spawn md5sum");
    child.stdin.take().unwrap().write_all(data).expect("write to md5sum");
    let out = child.wait_with_output().expect("md5sum output");
    assert!(out.status.success(), "md5sum exited with {}", out.status);
    String::from_utf8(out.stdout)
        .expect("md5sum utf8")
        .split_whitespace()
        .next()
        .expect("md5sum digest")
        .to_string()
}

#[test]
fn generated_is_fresh() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests");
    let mut actual: Vec<(String, String)> = std::fs::read_dir(&dir)
        .expect("read tests/")
        .map(|e| e.expect("dir entry").path())
        .filter(|p| p.extension().and_then(|x| x.to_str()) == Some("s"))
        .map(|p| {
            let name = p.file_name().unwrap().to_string_lossy().into_owned();
            (name, md5(&std::fs::read(&p).expect("read .s")))
        })
        .collect();
    actual.sort();
    let expected: Vec<(String, String)> =
        SOURCES.iter().map(|&(n, h)| (n.to_string(), h.to_string())).collect();
    assert_eq!(
        actual, expected,
        "\ntests/*.s changed since the generated tests were built - run: python3 tests/testgen.py\n"
    );
}
