// @generated by tests/testgen.py - do not edit.
// Regenerate with: python3 tests/testgen.py
//
// One #[test] per tests/*.s program. Each assembles its source, runs the
// onestep simulator one instruction at a time, and checks the register
// snapshot against that program's `;=` comments as their lines retire.

use std::io::Write;
use std::path::Path;
use std::process::{Command, Stdio};
use std::sync::Mutex;

use vea_sim::{assembler, memory, onestep, shared};

// The simulator's memory is process-global, so the program tests run one at a
// time under this lock.
static LOCK: Mutex<()> = Mutex::new(());

const CAP: u64 = 100_000;

// (1-based instruction index, source line, &[(reg, value)]) - checked every
// time that instruction retires.
type Inline = &'static [(usize, u32, &'static [(usize, u64)])];
// (retired-instruction count, source line, &[(reg, value)]) - from `;= at N:`.
type AtCount = &'static [(u64, u32, &'static [(usize, u64)])];
// (source line, &[(reg, value)]) - from `;= final:`, checked once halted.
type Final = (u32, &'static [(usize, u64)]);

macro_rules! src {
    ($name:literal) => {
        include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/tests/", $name))
    };
}

// Assemble `source`, run it to halt (or the cap), and assert every checkpoint.
fn check(source: &str, inline: Inline, at_count: AtCount, final_: Final) {
    let _guard = LOCK.lock().unwrap_or_else(|e| e.into_inner());
    memory::reset();
    let (image, rows) = assembler::assemble_listing(source).expect("program assembles");
    memory::load(0, &image).expect("image loads");
    let mut cpu = onestep::Processor::new();

    // Resolve each annotated instruction index to the address it loaded at.
    let inline: Vec<(u64, u32, &[(usize, u64)])> = inline
        .iter()
        .map(|&(idx, line, checks)| (rows[idx - 1].addr, line, checks))
        .collect();

    let mut steps = 0u64;
    while !cpu.halted() && steps < CAP {
        let pc = cpu.pc;
        cpu.cycle(1).expect("instruction executes without a fault");
        steps += 1;
        let (regs, completed) =
            shared::with(|s| (s.snapshot.regs, s.snapshot.completed_instrs));

        for &(addr, line, checks) in &inline {
            if addr == pc {
                for &(reg, want) in checks {
                    assert_eq!(regs[reg], want, "line {line}: r{reg} (pc {addr:#x})");
                }
            }
        }
        for &(count, line, checks) in at_count {
            if count == completed {
                for &(reg, want) in checks {
                    assert_eq!(regs[reg], want, "line {line}: r{reg} at instruction {count}");
                }
            }
        }
    }

    assert!(cpu.halted(), "program did not halt within {CAP} instructions");

    let regs = shared::with(|s| s.snapshot.regs);
    let (line, checks) = final_;
    for &(reg, want) in checks {
        assert_eq!(regs[reg], want, "line {line}: r{reg} at halt");
    }
}

#[test]
fn bitops() {
    check(
        src!("bitops.s"),
        &[
            (1, 5, &[(1, 3855)]),
            (2, 6, &[(2, 255)]),
            (3, 7, &[(3, 15)]),
            (4, 8, &[(4, 4095)]),
            (5, 9, &[(5, 4080)]),
            (6, 10, &[(6, 18446744073709547760)]),
            (7, 11, &[(7, 65280)]),
            (8, 12, &[(8, 4080)]),
            (9, 13, &[(9, 18446744073709551600)]),
            (10, 14, &[(10, 18446744073709551612)]),
            (11, 15, &[(11, 4611686018427387900)]),
        ],
        &[],
        (18, &[(3, 15), (6, 18446744073709547760), (10, 18446744073709551612)]),
    );
}

#[test]
fn branch_predicates() {
    check(
        src!("branch_predicates.s"),
        &[],
        &[],
        (39, &[(20, 63)]),
    );
}

#[test]
fn bubble_sort() {
    check(
        src!("bubble_sort.s"),
        &[
            (1, 4, &[(1, 16384)]),
        ],
        &[],
        (44, &[(10, 1), (11, 2), (12, 3), (13, 5), (14, 8)]),
    );
}

#[test]
fn factorial() {
    check(
        src!("factorial.s"),
        &[
            (1, 5, &[(1, 1)]),
            (2, 6, &[(2, 5)]),
        ],
        &[],
        (15, &[(1, 120), (2, 0)]),
    );
}

#[test]
fn fibonacci() {
    check(
        src!("fibonacci.s"),
        &[
            (1, 5, &[(1, 12288)]),
        ],
        &[],
        (29, &[(3, 55), (4, 11), (6, 55), (11, 1), (12, 55)]),
    );
}

#[test]
fn memcpy() {
    check(
        src!("memcpy.s"),
        &[
            (1, 5, &[(1, 4096)]),
            (2, 6, &[(2, 8192)]),
        ],
        &[],
        (31, &[(3, 16), (10, 4369), (11, 8738), (12, 13107), (13, 17476)]),
    );
}

#[test]
fn run_all_instrs_all_modes() {
    check(
        src!("run_all_instrs_all_modes.s"),
        &[
            (1, 7, &[(1, 100)]),
            (2, 8, &[(2, 100)]),
            (3, 9, &[(3, 105)]),
            (4, 10, &[(4, 200)]),
            (5, 11, &[(5, 100)]),
            (6, 12, &[(6, 100)]),
            (7, 13, &[(7, 103)]),
            (8, 14, &[(8, 0)]),
            (9, 15, &[(9, 18446744073709551615)]),
            (10, 16, &[(10, 200)]),
            (11, 17, &[(11, 50)]),
            (12, 18, &[(12, 18446744073709551615)]),
            (13, 19, &[(13, 300)]),
            (14, 20, &[(14, 25)]),
            (15, 23, &[(20, 16384)]),
            (17, 25, &[(1, 0)]),
            (18, 26, &[(1, 100)]),
            (20, 28, &[(15, 105)]),
        ],
        &[],
        (31, &[(1, 100), (12, 18446744073709551615), (14, 25), (15, 105)]),
    );
}

#[test]
fn sample_basics() {
    check(
        src!("sample_basics.s"),
        &[
            (1, 16, &[(1, 10)]),
            (2, 17, &[(2, 256)]),
            (3, 18, &[(3, 266)]),
            (4, 19, &[(4, 246)]),
            (5, 20, &[(5, 0)]),
            (6, 21, &[(6, 266)]),
            (7, 22, &[(7, 0)]),
            (8, 23, &[(8, 18446744073709551615)]),
            (9, 24, &[(9, 160)]),
            (10, 25, &[(10, 64)]),
            (11, 26, &[(11, 3)]),
        ],
        &[
            (21, 33, &[(11, 0)]),
        ],
        (35, &[(1, 10), (9, 160), (11, 0)]),
    );
}

#[test]
fn signed_vs_unsigned() {
    check(
        src!("signed_vs_unsigned.s"),
        &[
            (1, 5, &[(1, 18446744073709551611)]),
            (2, 6, &[(2, 3)]),
        ],
        &[],
        (23, &[(1, 18446744073709551611), (10, 1), (11, 0)]),
    );
}

#[test]
fn strlen() {
    check(
        src!("strlen.s"),
        &[
            (1, 4, &[(1, 20480)]),
        ],
        &[],
        (22, &[(3, 3), (4, 0)]),
    );
}

#[test]
fn sum_1_to_n() {
    check(
        src!("sum_1_to_n.s"),
        &[
            (1, 5, &[(1, 0)]),
            (2, 6, &[(2, 0)]),
            (3, 7, &[(3, 10)]),
        ],
        &[
            (5, 16, &[(1, 1), (2, 1)]),
        ],
        (17, &[(1, 55), (2, 10), (3, 10)]),
    );
}

// ---- freshness -----------------------------------------------------------

// (file name, md5sum) for every tests/*.s when these tests were generated.
const SOURCES: &[(&str, &str)] = &[
    ("bitops.s", "b70a921badffd68ddcb5808a6d48c3e0"),
    ("branch_predicates.s", "c2cefa6da51956309d435fb6f221707e"),
    ("bubble_sort.s", "9da74dd8a72ff9bebd09b1d258d1e3ce"),
    ("factorial.s", "f54d12d8b5d41009c20a97c6b0749787"),
    ("fibonacci.s", "fa4ceaa156ce4036b41202f5af7b9b9b"),
    ("memcpy.s", "ff23af2ed23e2d90f5b1cb254181e475"),
    ("run_all_instrs_all_modes.s", "c0c2b41998de6968f49e5d615c2341e3"),
    ("sample_basics.s", "4e95d761b1058c52f59b54aa676c0bc8"),
    ("signed_vs_unsigned.s", "6b1f33d0ced0a463fe0095ceda30a816"),
    ("strlen.s", "bc2843c7277f0e22631aee0da665b814"),
    ("sum_1_to_n.s", "04de3223d4fc14763541cfcf9305b80b"),
];

// Shell out to md5sum (the same digest the generator baked in).
fn md5(data: &[u8]) -> String {
    let mut child = Command::new("md5sum")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .expect("spawn md5sum");
    child.stdin.take().unwrap().write_all(data).expect("write to md5sum");
    let out = child.wait_with_output().expect("md5sum output");
    assert!(out.status.success(), "md5sum exited with {}", out.status);
    String::from_utf8(out.stdout)
        .expect("md5sum utf8")
        .split_whitespace()
        .next()
        .expect("md5sum digest")
        .to_string()
}

#[test]
fn generated_is_fresh() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests");
    let mut actual: Vec<(String, String)> = std::fs::read_dir(&dir)
        .expect("read tests/")
        .map(|e| e.expect("dir entry").path())
        .filter(|p| p.extension().and_then(|x| x.to_str()) == Some("s"))
        .map(|p| {
            let name = p.file_name().unwrap().to_string_lossy().into_owned();
            (name, md5(&std::fs::read(&p).expect("read .s")))
        })
        .collect();
    actual.sort();
    let expected: Vec<(String, String)> =
        SOURCES.iter().map(|&(n, h)| (n.to_string(), h.to_string())).collect();
    assert_eq!(
        actual, expected,
        "\ntests/*.s changed since the generated tests were built - run: python3 tests/testgen.py\n"
    );
}
