// @generated by tests/testgen.py from tests/sample_basics.s - do not edit.
// Regenerate with: python3 tests/testgen.py

use std::sync::Mutex;

use vea_sim::{assembler, memory, onestep, shared};

// Tests in one file share a process and the global simulator memory, so they
// run one at a time. Separate .s files are separate test binaries (separate
// processes) and do not contend.
static LOCK: Mutex<()> = Mutex::new(());

const SOURCE: &str =
    include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/tests/sample_basics.s"));

// (1-based instruction index, source line, [(reg, value)]) - checked every time
// that instruction retires.
const INLINE: &[(usize, u32, &[(usize, u64)])] = &[
    (1, 16, &[(1, 10)]),
    (2, 17, &[(2, 256)]),
    (3, 18, &[(3, 266)]),
    (4, 19, &[(4, 246)]),
    (5, 20, &[(5, 0)]),
    (6, 21, &[(6, 266)]),
    (7, 22, &[(7, 0)]),
    (8, 23, &[(8, 18446744073709551615)]),
    (9, 24, &[(9, 160)]),
    (10, 25, &[(10, 64)]),
    (11, 26, &[(11, 3)]),
];

// (retired-instruction count, source line, [(reg, value)]) - from `;= at N:`.
const AT_COUNT: &[(u64, u32, &[(usize, u64)])] = &[
    (21, 33, &[(11, 0)]),
];

// (source line, [(reg, value)]) - from `;= final:`, checked once halted.
const FINAL: (u32, &[(usize, u64)]) = (35, &[(1, 10), (9, 160), (11, 0)]);

const CAP: u64 = 100_000;

#[test]
fn sample_basics() {
    let _guard = LOCK.lock().unwrap_or_else(|e| e.into_inner());
    memory::reset();
    let (image, rows) = assembler::assemble_listing(SOURCE).expect("program assembles");
    memory::load(0, &image).expect("image loads");
    let mut cpu = onestep::Processor::new();

    // Resolve each annotated instruction index to the address it loaded at.
    let inline: Vec<(u64, u32, &[(usize, u64)])> = INLINE
        .iter()
        .map(|&(idx, line, checks)| (rows[idx - 1].addr, line, checks))
        .collect();

    let mut steps = 0u64;
    while !cpu.halted() && steps < CAP {
        let pc = cpu.pc;
        cpu.cycle(1).expect("instruction executes without a fault");
        steps += 1;
        let (regs, completed) =
            shared::with(|s| (s.snapshot.regs, s.snapshot.completed_instrs));

        for &(addr, line, checks) in &inline {
            if addr == pc {
                for &(reg, want) in checks {
                    assert_eq!(regs[reg], want, "line {line}: r{reg} (pc {addr:#x})");
                }
            }
        }
        for &(count, line, checks) in AT_COUNT {
            if count == completed {
                for &(reg, want) in checks {
                    assert_eq!(regs[reg], want, "line {line}: r{reg} at instruction {count}");
                }
            }
        }
    }

    assert!(cpu.halted(), "program did not halt within {CAP} instructions");

    let regs = shared::with(|s| s.snapshot.regs);
    let (line, checks) = FINAL;
    for &(reg, want) in checks {
        assert_eq!(regs[reg], want, "line {line}: r{reg} at halt");
    }
}
